config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  #get 'home/index'
  root to: "meetings#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings
  validates :username, presence: true
	validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
  end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /meetings or /meetings.json
  def index
    @currentTime = Time.zone.now
    @meetings = Meeting.all
    if user_signed_in?
      @meeting = current_user.meetings.build
    end
    
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    @currentTime = Time.zone.now
  end

  # GET /meetings/new
  def new
    @meeting = current_user.meetings.build
    @datePass = params[:start_date]
    @timePass = params[:start_time]
    @meetings = Meeting.all
    @currentTime = Time.zone.now
  end

  # GET /meetings/1/edit
  def edit
    @currentTime = Time.zone.now
  end

  # POST /meetings or /meetings.json
  def create
    #@meeting = Meeting.new(meeting_params)
    @meeting = current_user.meetings.build(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to root_path, notice: "Meeting was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def correct_user
    @meeting = current_user.meetings.find_by(id: params[:id])
    redirect_to meetings_path, notice: "Not Authorized To Edit This Meeting" if @meeting.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:start_date, :start_time, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid d-flex bd-highlight">
    <div class="p-2 flex-grow-1 bd-highlight">
      <%= link_to 'Reuniões', root_path, class:"navbar-brand" %>
    </div>
    
    <div class="nav-link p-2 bd-highlight" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">

        <% if user_signed_in? %>
          
          <li>
            <%= link_to 'Sair', destroy_user_session_path,method: :delete, class:"nav-link p-2 bd-highlight" %>
          </li>
          <li>
            <span class="nav-link disabled p-2 bd-highlight"><%= current_user.username %></span>
          </li>
        <% else %>
          <li>
            <%= link_to 'Cadastrar', new_user_registration_path, class:"nav-link p-2 bd-highlight" %>
          </li>

          <li>
            <%= link_to 'Entrar', new_user_session_path, class:"nav-link p-2 bd-highlight" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reuniao</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <% end %>
    <%= yield %>
  </body>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>

app/views/meetings/_form.html.erb
<div class="container w-25" >
  <div class="card mt-4">
    <div class="card-header d-flex justify-content-center">
      <h2>Area de Edição</h2>
    </div>
    <div class="card-body">
      <%= form_with(model: meeting, local: false) do |form| %>
        <% if meeting.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

            <ul>
              <% meeting.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form.text_field :start_date, value:meeting.start_date, type: :hidden %>
        <%= form.text_field :start_time, value:meeting.start_time, type: :hidden %>

        <div class="mb-3">
          <span class= 'form-control'>Data: <%= meeting.start_date %></span>
        </div>
        <div class="mb-3">
          <span class= 'form-control'>Hora: <%= meeting.start_time.strftime("%H")+":00" %></span>
        </div>

        <div class="mb-3">
          <%= form.label :description, "Descrição" %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <%= form.text_field :user_id, id: :meeting_user_id, class: 'form-control', value:current_user.id, type: :hidden %>

        <div class="actions mb-3">
          <%= form.submit class: "btn btn-primary"%>
        </div>
      <% end %>
      <div class ="d-flex justify-content-between">
        <%= link_to '<button type="button" class="btn btn-danger">Voltar</button>'.html_safe, meetings_path %>
        <%= link_to '<button type="button" class="btn btn-primary">Exibir</button>'.html_safe, @meeting %>
      </div>
    </div>
  </div>
</div>


  

app/views/meetings/_formModal.html.erb
<% horaSomadaFuso = time.to_i + 2 %>
<% horaConvertidaBrasil = date+" "+time+":00"+" -3:00"%>
<% horaTimeConvertida = horaConvertidaBrasil.to_time %>

<% if @currentTime < horaTimeConvertida%>
  <div class="card-body">
    <%= form_with(model: meeting, local: false) do |form| %>
      <% if meeting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

          <ul>
            <% meeting.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.text_field :start_date, value:date, type: :hidden %>
      <%= form.text_field :start_time, value:time, type: :hidden %>

      <div class="mb-3">
        <span class= 'form-control'>Data: <%= date %></span>
      </div>
      <div class="mb-3">
        <span class= 'form-control'>Hora: <%= time+":00" %></span>
      </div>

      <div class="mb-3">
        <%= form.label :description, "Descrição" %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <%= form.text_field :user_id, id: :meeting_user_id, class: 'form-control', value:current_user.id, type: :hidden %>

      <div class="actions">
        <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% else %>
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
  </svg>
  <div class="container">
    <div class="alert alert-danger d-flex align-items-center" role="alert">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
      <h1>Você não pode marcar reunião no passado!!</h1>
    </div>
  </div>
<% end %>

  

app/views/meetings/edit.html.erb
<%= render 'form', meeting: @meeting %>

app/views/meetings/index.html.erb
<% if user_signed_in? %>
    <%= week_calendar do |date| %>
    <% end %>
<% else %>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
    </svg>
    <div class="container">
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <h1>Para verificar as reunioes você precisa estar logado!</h1>
        </div>
    </div>
<% end %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<% horaConvertidaBrasil = @meeting.start_date.to_s+" "+@meeting.start_time.strftime("%H:%M")+" -3"%>
<div class="container w-25" >
  <div class="card mt-4">
    <div class="card-body">
      <div class="mb-3">
        <p>
          <strong >Start date:</strong>
          <input class="form-control" type="text" placeholder="<%= @meeting.start_date %>" aria-label="Disabled input example" disabled>
        </p>
      </div>
      <div class="mb-3">
        <p>
          <strong >Start time:</strong>
          <input class="form-control" type="text" placeholder="<%= @meeting.start_time.strftime("%H:%M") %>" aria-label="Disabled input example" disabled>
        </p>
      </div>
      <div class="mb-3">
        <strong >Descrição:</strong>
        <div class="form-floating">
          <textarea class="form-control" placeholder="" id="floatingTextarea2" style="height: 100px" disabled><%= @meeting.description %></textarea>
        </div>
      </div>
      <div class="mb-3">
        <p class="d-flex justify-content-between">
          <%= link_to 'Voltar', meetings_path, class: "btn btn-danger" %>
          <% if @currentTime < horaConvertidaBrasil && current_user.id == @meeting.user_id%>
            <%= link_to 'Editar', edit_meeting_path(@meeting), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<% reunioes = @meetings.select("meetings.id,meetings.description,meetings.start_date,meetings.start_time,users.username").joins(:user)%>

<div class="navbar navbar-light bg-info">
  <%= link_to t('simple_calendar.previous', default: 'Voltar semana'), calendar.url_for_previous_view , class:"btn btn-outline-success" %>
  <h5><%= t('date.month_names')[start_date.month] %><%= t('simple_calendar.week', default: ' Semana') %> <%= calendar.week_number %></h5>
  <%= link_to t('simple_calendar.next', default: 'Proxima semana'), calendar.url_for_next_view , class:"btn btn-outline-success"%>
</div>

<table class="table table-info">
  <thead>
    <tr>
      <th>Horario</th>
      <th>Segunda-Feira</th>
      <th>Terça-Feira</th>
      <th>Quarta-Feira</th>
      <th>Quinta-Feira</th>
      <th>Sexta-Feira</th>
    </tr>
  </thead>
  <tbody>
    <td></td>
    <% date_range.each_slice(7) do |week| %>
      <% week.pop(2) %>

      <% week.each do |day| %>
        <%= content_tag :td, class: calendar.td_classes_for(day) do %>
          <%= day.strftime("%d/%m/%Y") %>
        <% end %>
      <% end %>

      <% 6.upto(23).each do |hour| %>
        <tr>
          <td>
            <%= Time.parse("#{hour}:00").strftime("%H:%M") %>
          </td>                    
          
          <% week.each do |day| %>
            <td>               
                <% temReuniaoNoDiaNaHora = false %>

                <% reunioes.each do |reuniao| %>

                  <%if day == reuniao.start_date && hour == reuniao.start_time.strftime("%H").to_i%>
                    <div>
                      Criado por: <strong><%= link_to reuniao.username, reuniao %></strong> | <%= link_to 'Apagar', reuniao,remote: :true, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
                    </div>
                    <% temReuniaoNoDiaNaHora = true %>
                  <% end %>

                <% end %>
                
                <% if !temReuniaoNoDiaNaHora %>
                  <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal<%=day%><%=hour%>">
                    Disponivel
                  </button>
                  <!-- Modal -->
                  <div class="modal fade" id="exampleModal<%=day%><%=hour%>" tabindex="-1" aria-hidden="true">
                      <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header d-flex justify-content-center">
                                <h5 class="modal-title">Crie sua Reunião</h5>
                            </div>
                            <div class="modal-body">
                                <%= render 'formModal', {meeting: @meeting,date: day.strftime("%F"),time: hour.to_s } %>               
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                            </div>
                          </div>
                      </div>
                  </div>
                  
                <% end %>
                
            </td>
          <% end %>
          
        </tr>      
      <% end %>

    <% end %>
  </tbody>
</table>